// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZdnS4FWO0HaC6_I8Ta8NER1YRvGVimNo',
    appId: '1:261667843517:web:ad37cafbe1b39d425b36d4',
    messagingSenderId: '261667843517',
    projectId: 'm-9f5e8',
    authDomain: 'm-9f5e8.firebaseapp.com',
    databaseURL: 'https://m-9f5e8-default-rtdb.firebaseio.com',
    storageBucket: 'm-9f5e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_GES4fhFG86K8Px3tVNDswnaTpKH1bUM',
    appId: '1:261667843517:android:1c19a78cecfb9e685b36d4',
    messagingSenderId: '261667843517',
    projectId: 'm-9f5e8',
    databaseURL: 'https://m-9f5e8-default-rtdb.firebaseio.com',
    storageBucket: 'm-9f5e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt_qSqFre8dcr9FsMgVpSLQGa-G4_Xesg',
    appId: '1:261667843517:ios:44dd9cca0b2158d85b36d4',
    messagingSenderId: '261667843517',
    projectId: 'm-9f5e8',
    databaseURL: 'https://m-9f5e8-default-rtdb.firebaseio.com',
    storageBucket: 'm-9f5e8.firebasestorage.app',
    iosBundleId: 'com.example.paypalm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZdnS4FWO0HaC6_I8Ta8NER1YRvGVimNo',
    appId: '1:261667843517:web:cf7d822c7490d9465b36d4',
    messagingSenderId: '261667843517',
    projectId: 'm-9f5e8',
    authDomain: 'm-9f5e8.firebaseapp.com',
    databaseURL: 'https://m-9f5e8-default-rtdb.firebaseio.com',
    storageBucket: 'm-9f5e8.firebasestorage.app',
  );
}
